defaults:
  - /defaults.yaml

experiment:
  run_name: nearest_fashion_mnist
  tags: [baseline, nearest, fashion_mnist]

dataset:
  name: fashion_mnist
  split: train
  download: true
  batch_size: 512
  subset_size: null # Use full dataset for nearest dataset computation

model:
  name: nearest_dataset
  params: {}

metrics:
  baseline_path: "data/models/baseline_unet/fashion_mnist/ckpt_epoch_200.pt"